import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  homeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a202c', 
    paddingVertical: 50, 
    paddingHorizontal: 20,
    paddingBottom: 100, 
  },
  homeTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#90cdf4', 
    textAlign: 'center',
    marginBottom: 20,
  },
  homeSubtitle: {
    fontSize: 16,
    color: '#cbd5e0', 
    textAlign: 'center',
    marginBottom: 40,
  },
  homeButton: {
    backgroundColor: '#667eea', 
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  homeButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },

  profileContainer: {
    flex: 1,
    backgroundColor: '#1a202c', 
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  profileBackButton: {
    position: 'absolute',
    top: 40,
    left: 20,
    zIndex: 1,
    padding: 10,
  },
  profileCard: {
    backgroundColor: '#2d3748', 
    borderRadius: 15,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
    width: '90%',
    maxWidth: 400,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: '#90cdf4', 
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#e2e8f0', 
    marginBottom: 10,
  },
  profileEmail: {
    fontSize: 16,
    color: '#cbd5e0', 
    marginBottom: 15,
  },
  profileBio: {
    fontSize: 14,
    color: '#a0aec0', 
    textAlign: 'center',
    lineHeight: 20,
  },

  helloContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a202c', 
    padding: 20,
  },
  helloTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#90cdf4', 
    textAlign: 'center',
    marginBottom: 30,
  },
  helloImage: {
    width: 250,
    height: 180,
    borderRadius: 10,
    marginBottom: 40,
    borderWidth: 2,
    borderColor: '#4a5568', 
  },
  helloButton: {
    backgroundColor: '#667eea', 
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  helloButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  counterContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a202c', 
    padding: 20,
  },
  counterTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#90cdf4', 
    marginBottom: 30,
  },
  counterCountText: {
    fontSize: 80,
    fontWeight: 'bold',
    color: '#e2e8f0',
    marginBottom: 40,
    backgroundColor: '#4a5568',
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 20,
    minWidth: 150,
    textAlign: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  counterButtonContainer: {
    flexDirection: 'row',
    width: '80%',
    justifyContent: 'space-around',
  },
  counterButton: {
    backgroundColor: '#667eea', 
    width: 80,
    height: 80,
    borderRadius: 40, 
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  counterButtonText: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
  },


  listContainer: {
    flex: 1,
    backgroundColor: '#1a202c', 
    padding: 20,
    width: '100%',
  },
  listTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#90cdf4', 
    textAlign: 'center',
    marginBottom: 20,
  },
  listContent: {
    paddingBottom: 20, 
  },
  listCard: {
    backgroundColor: '#2d3748',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  listCardName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#e2e8f0', 
    marginBottom: 5,
  },
  listCardNPM: {
    fontSize: 16,
    color: '#cbd5e0', 
  },

  formContainer: {
    flex: 1,
    backgroundColor: '#1a202c',
    padding: 20,
    width: '100%',
  },
  formTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#90cdf4', 
    textAlign: 'center',
    marginBottom: 20,
  },
  formInputGroup: {
    marginBottom: 15,
  },
  formLabel: {
    fontSize: 16,
    marginBottom: 8,
    color: '#cbd5e0', 
    fontWeight: 'bold',
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#4a5568', 
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#2d3748', 
    color: '#e2e8f0', 
  },
  formButton: {
    backgroundColor: '#48bb78', 
    paddingVertical: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  formButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
});